/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UtOfP0jatGV
 */
import Link from "next/link"

export function Nav () {
  return (
    <div className="flex flex-col h-screen w-full">
      <div className="flex flex-1 min-h-0 flex-col">
        <main className="flex-1 min-h-0 bg-gray-100 dark:bg-gray-800" />
        <nav className="flex h-16 shrink-0 border-t items-center px-4 md:px-6 bg-gray-100 dark:bg-gray-800">
          <Link
            className="flex flex-1 flex-col items-center justify-center text-xs font-medium transition-colors hover:text-gray-900 dark:hover:text-gray-50"
            href="#"
          >
            <HomeIcon className="h-5 w-5" />
            Home
          </Link>
          <Link
            className="flex flex-1 flex-col items-center justify-center text-xs font-medium transition-colors hover:text-gray-900 dark:hover:text-gray-50"
            href="#"
          >
            <BookmarkIcon className="h-5 w-5" />
            Favorites
          </Link>
          <Link
            className="flex flex-1 flex-col items-center justify-center text-xs font-medium transition-colors hover:text-gray-900 dark:hover:text-gray-50"
            href="#"
          >
            <SearchIcon className="h-5 w-5" />
            Search
          </Link>
          <Link
            className="flex flex-1 flex-col items-center justify-center text-xs font-medium transition-colors hover:text-gray-900 dark:hover:text-gray-50"
            href="#"
          >
            <CalendarIcon className="h-5 w-5" />
            Calendar
          </Link>
        </nav>
      </div>
    </div>
  )
}


function HomeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function BookmarkIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function CalendarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}
